// Generated by CoffeeScript 2.5.0
(function() {
  var CoffeeScript, coffee, i, len, method, methods;

  require('./prelude');

  CoffeeScript = require('coffeescript');

  methods = ['all', 'any', 'rep', 'case', 'flip', 'chr', 'rng', 'but', 'chk', 'set', 'max', 'exclude', 'add', 'sub', 'm', 't'];

  coffee = `global.DebugParser = class DebugParser extends Parser`;

  for (i = 0, len = methods.length; i < len; i++) {
    method = methods[i];
    coffee += `
${method}: (args...)->
  debug "${method}"
  super.${method} args...
`.replace(/^/gm, '  ');
  }

  eval(CoffeeScript.compile(coffee, {
    bare: true
  }));

}).call(this);
