// Generated by CoffeeScript 2.5.0
(function() {
  var Grammar;

  require('./grammar-spec');

  Grammar = (function() {
    class Grammar extends GrammarSpec {
      //----------------------------------------------------------------
      // Required hand written rules
      //----------------------------------------------------------------
      start_of_line() {
        return this.pos === 0 || this.input[this.pos - 1] === "\n";
      }

      end_of_stream() {
        return this.pos >= this.len;
      }

      empty() {
        return true;
      }

      auto_detect_indent() {
        return 1;
      }

    };

    Grammar.prototype.m = 0;

    Grammar.prototype.t = 'keep';

    return Grammar;

  }).call(this);

  global.Grammar = Grammar;

}).call(this);
